model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 64
#  loss_type: 'H'
  beta: 16
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 35
  Capacity_max_iter: 10000

data_params:
  dir_path: "/media/matt/4TBInternal/zzFootball/"
#  "/media/matt/4TBInternal/zzFootball/20160910_MUvsEasternMichigan/For_Upload/"
  train_batch_size: 32
  val_batch_size:  32
  crop_size: [72,128]
  num_workers: 4

exp_params:
  LR: 0.0025
  weight_decay: 0.0
  scheduler_gamma: 0.98
  kld_weight: 0.00025
  manual_seed: 1265
  retain_first_backpass: True

trainer_params:
#  gpus: [0]
  accumulate_grad_batches: 4
  auto_lr_find: True
  auto_scale_batch_size: True
  accelerator: 'gpu'
  devices: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: 'BetaVAE'